# Generated by Django 5.1.5 on 2025-03-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
