# Generated by Django 5.1.5 on 2025-03-03 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dbz", "0002_order_latitude_order_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_boy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_delivery_boy",
            field=models.BooleanField(default=False),
        ),
    ]
